type LineObj = {
	[line: string]: {
		branch: Boolean;
		line: string;
		stations?: string[];
		top?: string[][];
		bottom?: string[][];
	};
};

type StationDict = {
	[station: string]: string;
};

const lines: LineObj = {
	bakerloo: {
		branch: false,
		line: 'bakerloo',
		stations: [
			'HAW',
			'KNT',
			'SKT',
			'NWM',
			'WEM',
			'SPK',
			'HSD',
			'WJN',
			'KGN',
			'QPK',
			'KPK',
			'MDV',
			'WAR',
			'PAD',
			'ERB',
			'MYB',
			'BST',
			'RPK',
			'OXC',
			'PIC',
			'CHX',
			'EMB',
			'WLO',
			'LAM',
			'ELE'
		]
	},
	central: {
		branch: true,
		line: 'central',
		top: [
			['WRP', 'RUG', 'SRP', 'NHT', 'GFD', 'PER', 'HLN', 'NAC'],
			['EBY', 'WAC', 'NAC']
		],
		bottom: [
			[
				'NAC',
				'EAC',
				'WCT',
				'SHB',
				'HPK',
				'NHG',
				'QWY',
				'LAN',
				'MAR',
				'BDS',
				'OXC',
				'TCR',
				'HOL',
				'CYL',
				'STP',
				'BNK',
				'LST',
				'BNG',
				'MLE',
				'SFD',
				'LEY',
				'LYS'
			],
			[
				'NAC',
				'EAC',
				'WCT',
				'SHB',
				'HPK',
				'NHG',
				'QWY',
				'LAN',
				'MAR',
				'BDS',
				'OXC',
				'TCR',
				'HOL',
				'CYL',
				'STP',
				'BNK',
				'LST',
				'BNG',
				'MLE',
				'SFD',
				'LEY',
				'LYS',
				'SNB',
				'SWF',
				'WFD',
				'BHL',
				'LTN',
				'DEB',
				'THB',
				'EPP'
			],
			[
				'NAC',
				'EAC',
				'WCT',
				'SHB',
				'HPK',
				'NHG',
				'QWY',
				'LAN',
				'MAR',
				'BDS',
				'OXC',
				'TCR',
				'HOL',
				'CYL',
				'STP',
				'BNK',
				'LST',
				'BNG',
				'MLE',
				'SFD',
				'LEY',
				'LYS',
				'WSD',
				'RED',
				'GHL',
				'NEP',
				'BDE',
				'FLP',
				'HAI',
				'GRH',
				'CHG',
				'ROD',
				'WFD'
			]
		]
	},
	piccadilly: {
		branch: true,
		line: 'piccadilly',
		top: [
			[
				'CFS',
				'OAK',
				'SGT',
				'AGR',
				'BGR',
				'WGN',
				'TPL',
				'TPL',
				'MNR',
				'FPK',
				'ARL',
				'HRD',
				'CRD',
				'KXX',
				'RSQ',
				'HOL',
				'COV',
				'LSQ',
				'PIC',
				'GPK',
				'HPC',
				'KNB',
				'SKN',
				'GRD',
				'ECT',
				'BCT',
				'HMD',
				'TGR'
			]
		],
		bottom: [
			['TGR', 'ACT', 'ECM', 'NEL', 'PRY', 'ALP', 'STN', 'SHL', 'SHR', 'RLN', 'ETE', 'RUM', 'RUI', 'ICK', 'HDN', 'UXB'],
			['TGR', 'ACT', 'SEL', 'NFD', 'BOS', 'OST', 'HNE', 'HNC', 'HNW', 'HTX', 'HRC', 'HTF', 'HTC'],
			['TGR', 'ACT', 'SEL', 'NFD', 'BOS', 'OST', 'HNE', 'HNC', 'HNW', 'HTX', 'HRC', 'HRV']
		]
	},
	jubilee: {
		branch: false,
		line: 'jubilee',
		stations: [
			'STA',
			'CPK',
			'QBY',
			'KBY',
			'WPK',
			'NEA',
			'DHL',
			'WLG',
			'KIL',
			'WHD',
			'FRD',
			'SWC',
			'SJW',
			'BST',
			'BDS',
			'GPK',
			'WMS',
			'WLO',
			'SWK',
			'LON',
			'BER',
			'CWR',
			'CWF',
			'NGW',
			'CAT',
			'WEH',
			'SFD'
		]
	},
	metropolitan: {
		branch: true,
		line: 'metropolitan',
		top: [
			['AME', 'CLF', 'CWD', 'RKY', 'MPK', 'NWD', 'NWH', 'PIN', 'NHR', 'HOH'],
			['CHE', 'CLF', 'CWD', 'RKY', 'MPK', 'NWD', 'NWH', 'PIN', 'NHR', 'HOH'],
			['WAT', 'CRX', 'MPK', 'NWD', 'NWH', 'PIN', 'NHR', 'HOH'],
			['UXB', 'HDN', 'ICK', 'RUI', 'RUM', 'ETE', 'RLN', 'WHR', 'HOH']
		],
		bottom: [['HOH', 'NWP', 'PRD', 'WPK', 'FRD', 'BST', 'GPS', 'ESQ', 'KXX', 'FAR', 'BAR', 'MGT', 'LST', 'ALD']]
	},
	victoria: {
		branch: false,
		line: 'victoria',
		stations: [
			'WAL',
			'BHR',
			'TTH',
			'SVS',
			'FPK',
			'HBY',
			'KXX',
			'EUS',
			'WST',
			'OXC',
			'GPK',
			'VIC',
			'PIM',
			'VUX',
			'STK',
			'BRX'
		]
	},
	northern: {
		branch: true,
		line: 'northern',
		top: [
			['HBT', 'TOT', 'WSP', 'WFY', 'FYC', 'FYC', 'EFY', 'HIG', 'ARC', 'TPK', 'KTN', 'CTN'],
			['MHE', 'FYC', 'EFY', 'HIG', 'ARC', 'TPK', 'KTN', 'CTN'],
			['EDG', 'BUR', 'COL', 'HND', 'BTX', 'GGR', 'HMP', 'BPK', 'CHF', 'CTN']
		],
		bottom: [
			['CTN', 'MCR', 'EUS', 'WST', 'GST', 'TCR', 'LSQ', 'CHX', 'EMB', 'WLO', 'KEN', 'NIE', 'BAT'],
			[
				'CTN',
				'EUS',
				'KXX',
				'ANG',
				'OLD',
				'MGT',
				'BNK',
				'LON',
				'BOR',
				'ELE',
				'KEN',
				'OVL',
				'STK',
				'CPN',
				'CPC',
				'CPS',
				'BAL',
				'TBE',
				'TBY',
				'CLW',
				'SWM',
				'MOR'
			]
		]
	},
	circle: {
		branch: false,
		line: 'circle',
		stations: [
			'HMS',
			'GOR',
			'SBM',
			'WOL',
			'LAT',
			'LAD',
			'WBP',
			'ROO',
			'PAD',
			'ERD',
			'BST',
			'GPS',
			'ESQ',
			'KXX',
			'FAR',
			'BAR',
			'MGT',
			'LST',
			'ALD',
			'THL',
			'MON',
			'CST',
			'MAN',
			'BLF',
			'TEM',
			'EMB',
			'WMS',
			'SJP',
			'VIC',
			'SSQ',
			'SKN',
			'GRD',
			'HST',
			'NHG',
			'BAY',
			'PAD',
			'ERD'
		]
	},
	'hammersmith-city': {
		branch: false,
		line: 'hammersmith-city',
		stations: [
			'HMS',
			'GOR',
			'SBM',
			'WOL',
			'LAT',
			'LAD',
			'WBP',
			'ROO',
			'PAD',
			'ERD',
			'BST',
			'GPS',
			'ESQ',
			'KXX',
			'FAR',
			'BAR',
			'MGT',
			'LST',
			'ALE',
			'WCL',
			'STG',
			'MLE',
			'BWR',
			'BBB',
			'WEH',
			'PLW',
			'UPK',
			'EHM',
			'BKG'
		]
	},
	district: {
		branch: true,
		line: 'district',
		top: [
			['EBY', 'ECM', 'ACT', 'CHP', 'TGR', 'STB', 'RCP', 'HMD', 'BCT', 'WKN', 'ECT'],
			['RMD', 'KEW', 'GUN', 'TGR', 'STB', 'RCP', 'HMD', 'BCT', 'WKN', 'ECT'],
			['OLY', 'ECT'],
			['WDN', 'WMP', 'SFS', 'EPY', 'PUT', 'PGR', 'FBY', 'WBT', 'ECT']
		],
		bottom: [
			['ECT', 'HST', 'NHG', 'BAY', 'PAD', 'ERD'],
			[
				'ECT',
				'GRD',
				'SKN',
				'SSQ',
				'VIC',
				'SJP',
				'WMS',
				'EMB',
				'TEM',
				'BLF',
				'MAN',
				'CST',
				'MON',
				'THL',
				'ALE',
				'WCL',
				'STG',
				'MLE',
				'BWR',
				'BBB',
				'WEH',
				'PLW',
				'UPK',
				'EHM',
				'BKG',
				'UPY',
				'BEC',
				'DGH',
				'DGE',
				'EPK',
				'HCH',
				'UPB',
				'UPM'
			]
		]
	},
	'elizabeth-east': {
		branch: true,
		line: 'elizabeth',
		top: [
			['RDG', 'TFD', 'MDH', 'TLW', 'BHM', 'SGH', 'LGY', 'IVR', 'WDT', 'HAH'],
			['HRF', 'HTC', 'HAH'],
			['HTV', 'HTC', 'HAH']
		],
		bottom: [
			['HAH', 'SAL', 'HWL', 'WEL', 'EBY', 'AML', 'PAD'],
			['LST', '']
		]
	},
	'elizabeth-west': {
		branch: false,
		line: 'elizabeth',
		stations: ['LST', 'SFD', 'MLD', 'FGT', 'MNP', 'IFD', 'SVK', 'GDM', 'CWH', 'RFD', 'GDP', 'HWD', 'BWD', 'SND']
	},
	'elizabeth-central': {
		branch: false,
		line: 'elizabeth',
		stations: ['PAD', 'TCR', 'FAR', 'LST', 'WCL', 'CWF', 'CUH', 'WOO', 'ABW']
	},
	'overground_WTJ-EUS': {
		branch: false,
		line: 'overground',
		stations: [
			'WTJ',
			'WFH',
			'BSH',
			'CEP',
			'HTE',
			'HDL',
			'HAW',
			'KNT',
			'SKT',
			'NWM',
			'WEM',
			'SPK',
			'HSD',
			'WJN',
			'KGN',
			'QPK',
			'KBN',
			'SOH',
			'EUS'
		]
	},
	'overground_GPO-BKG': {
		branch: false,
		line: 'overground',
		stations: ['GPO', 'UHL', 'CRH', 'HRY', 'STO', 'BHR', 'WMW', 'LEM', 'LER', 'WNP', 'WGR', 'BKG']
	},
	overground_HBY: {
		branch: true,
		line: 'overground',
		top: [['HBY', 'CNN', 'DLJ', 'HGG', 'HOX', 'SDC', 'WCL', 'SHA', 'WPE', 'ROE', 'CWR', 'SUQ']],
		bottom: [
			['SUQ', 'NWX'],
			['SUQ', 'NXG', 'BCY', 'HPA', 'FOH', 'SYD', 'CRP'],
			['SUQ', 'NXG', 'BCY', 'HPA', 'FOH', 'SYD', 'PNW', 'ANZ', 'NJN', 'WCY'],
			['SUQ', 'NXG', 'BCY', 'HPA', 'FOH', 'SYD', 'QRP', 'PMR', 'DMH', 'CHS', 'WWR', 'CLH']
		]
	},
	overground_LST: {
		branch: true,
		line: 'overground',
		top: [
			['HKD', 'RRD', 'SNT', 'SFH', 'SVS', 'BRG', 'WHL', 'SST', 'EMG', 'BHP', 'EFT'],
			['HKD', 'RRD', 'SNT', 'SFH', 'SVS', 'BRG', 'WHL', 'SST', 'EMG', 'SBY', 'TST', 'TBG', 'CHT'],
			['HKD', 'CPT', 'SJS', 'WAL', 'WOS', 'HGP', 'CFD']
		],
		bottom: [['LST', 'BNG', 'CBH', 'LFD', 'HKD']]
	},
	overground_SFD: {
		branch: true,
		line: 'overground',
		top: [
			['RMD', 'KEW', 'GUN', 'SAT', 'ACC', 'WJN'],
			['CLJ', 'IMW', 'WBT', 'OLY', 'SHB', 'WJN']
		],
		bottom: [
			[
				'WJN',
				'KNR',
				'BSP',
				'BSY',
				'WHD',
				'FNY',
				'HDH',
				'GPO',
				'KTW',
				'CMD',
				'CIR',
				'HBY',
				'CNN',
				'DLK',
				'HKC',
				'HMN',
				'HKW',
				'SFD'
			]
		]
	},
	overground_UPM: {
		branch: false,
		line: 'overground',
		stations: ['RFD', 'EMP', 'UPM']
	},
	tram: {
		branch: true,
		line: 'tram',
		top: [
			[
				'WDN',
				'DDN',
				'MRP',
				'MRD',
				'PBR',
				'BGW',
				'MTM',
				'MTJ',
				'BDL',
				'TRL',
				'AMP',
				'WDM',
				'WLP',
				'RVC',
				'CEN',
				'WCY',
				'WLR',
				'ECR',
				'LEB',
				'SAN'
			],
			[
				'WDN',
				'DDN',
				'MRP',
				'MRD',
				'PBR',
				'BGW',
				'MTM',
				'MTJ',
				'BDL',
				'TRL',
				'AMP',
				'WDM',
				'WLP',
				'CCS',
				'GGS',
				'ECR',
				'LEB',
				'SAN'
			]
		],
		bottom: [
			['SAN', 'LPK', 'CLN', 'GVH', 'ADV', 'FLW', 'KHD', 'NAD'],
			['SAN', 'ADS', 'BSL', 'WDS', 'ARN', 'ELM'],
			['SAN', 'ADS', 'BSL', 'WDS', 'ARN', 'HRD', 'BKB', 'AVR', 'BCR', 'BCJ']
		]
	},
	'waterloo-city': {
		branch: false,
		line: 'waterloo-city',
		stations: ['WLO', 'BNK']
	},
	'cable-car': {
		branch: false,
		line: 'cable-car',
		stations: ['EGP', 'EMD']
	},
	'dlr_E-W': {
		branch: true,
		line: 'dlr',
		top: [
			['BNK', 'SHA', 'LIM', 'WES'],
			['TOG', 'SHA', 'LIM', 'WES']
		],
		bottom: [
			['WES', 'POP', 'BLA', 'EAI', 'CAT', 'WST', 'PDK', 'LCA', 'KGV', 'WOA'],
			['WES', 'POP', 'BLA', 'EAI', 'CAT', 'ROV', 'CUH', 'PRR', 'ROA', 'BEP', 'CYP', 'GAR', 'BEC'],
			['WES', 'WIQ', 'CWF', 'HEW', 'SOW', 'CRO', 'MUD', 'ISG', 'CUS', 'GRE', 'DEB', 'ELR', 'LEW']
		]
	},
	'dlr_N-S': {
		branch: true,
		line: 'dlr',
		top: [['STI', 'SFD', 'SHS', 'ABR', 'WEH', 'STL', 'CAT']],
		bottom: [
			['CAT', 'WST', 'PDK', 'LCA', 'KGV', 'WOA'],
			['CAT', 'ROV', 'CUH', 'PRR', 'ROA', 'BEP', 'CYP', 'GAR', 'BEC']
		]
	},
	'dlr_SFD-LEW': {
		branch: false,
		line: 'dlr',
		stations: [
			'STI',
			'SFD',
			'PML',
			'DER',
			'LAP',
			'ALS',
			'POP',
			'WIQ',
			'CWF',
			'HEW',
			'SOW',
			'CRO',
			'MUD',
			'ISG',
			'CUS',
			'GRE',
			'DEB',
			'ELR',
			'LEW'
		]
	},
	OSI: {
		branch: false,
		line: 'OSI',
		stations: [
			'HLN',
			'PRY',
			'HMS',
			'HMD',
			'CRD',
			'CIR',
			'CMD',
			'CTN',
			'FRD',
			'FNY',
			'EUS',
			'ESQ',
			'WCT',
			'WOL',
			'SOH',
			'SWC',
			'THL',
			'TOG',
			'ROV',
			'EMD',
			'NGW',
			'EGP',
			'KNT',
			'NWP',
			'STO',
			'SVS',
			'WAL',
			'WMW',
			'HNY',
			'MNR',
			'ARC',
			'UHL',
			'WAN',
			'FGT',
			'CHS',
			'CPN',
			'SWM',
			'MRD',
			'NWX',
			'NXG'
		]
	}
};

const stations: StationDict = {
	'Abbey Road': 'ABR',
	'Abbey Wood': 'ABW',
	'Acton Central': 'ACC',
	'Acton Mainline': 'AML',
	'Acton Town': 'ACT',
	Addiscombe: 'ADS',
	'Addington Village': 'ADV',
	Aldgate: 'ALD',
	'Aldgate East': 'ALE',
	'All Saints': 'ALS',
	Alperton: 'ALP',
	Amersham: 'AME',
	'Ampere Way': 'AMP',
	Anerley: 'ANZ',
	Angel: 'ANG',
	Archway: 'ARC',
	Arena: 'ARN',
	'Arnos Grove': 'AGR',
	Arsenal: 'ARL',
	'Avenue Road': 'AVR',
	'Baker Street': 'BST',
	Balham: 'BAL',
	Bank: 'BNK',
	Barbican: 'BAR',
	Barking: 'BKG',
	Barkingside: 'BDE',
	'Barons Court': 'BCT',
	'Battersea Power Station': 'BAT',
	Bayswater: 'BAY',
	'Beckenham Junction': 'BCJ',
	'Beckenham Road': 'BCR',
	Beckton: 'BEC',
	'Beckton Park': 'BEP',
	Becontree: 'BEC',
	'Beddington Lane': 'BDL',
	'Belgrave Walk': 'BGW',
	'Belsize Park': 'BPK',
	Bermondsey: 'BER',
	'Bethnal Green': 'BNG',
	Birkbeck: 'BKB',
	Blackfriars: 'BLF',
	'Blackhorse Road': 'BHR',
	'Blackhorse Lane': 'BSL',
	Blackwall: 'BLA',
	'Bond Street': 'BDS',
	Borough: 'BOR',
	'Boston Manor': 'BOS',
	'Bounds Green': 'BGR',
	'Bow Church': 'BOC',
	'Bow Road': 'BWR',
	'Brent Cross': 'BTX',
	Brixton: 'BRX',
	Brockley: 'BCY',
	'Bromley by Bow': 'BBB',
	Brondesbury: 'BSY',
	'Brondesbury Park': 'BSP',
	Brentwood: 'BWD',
	'Bruce Grove': 'BRG',
	'Buckhurst Hill': 'BHL',
	Burnham: 'BHM',
	'Burnt Oak': 'BUR',
	'Bush Hill Park': 'BHP',
	Bushey: 'BSH',
	'Caledonian Road': 'CRD',
	'Caledonian Road & Barnsbury': 'CIR',
	'Cambridge Heath': 'CBH',
	'Camden Road': 'CMD',
	'Camden Town': 'CTN',
	'Canada Water': 'CWR',
	'Canary Wharf': 'CWF',
	'Canning Town': 'CAT',
	'Cannon Street': 'CST',
	Canonbury: 'CNN',
	'Canons Park': 'CPK',
	'Carpenders Park': 'CEP',
	Centrale: 'CEN',
	'Chadwell Heath': 'CWH',
	'Chalfont & Latimer': 'CLF',
	'Chalk Farm': 'CHF',
	'Chancery Lane': 'CYL',
	'Charing Cross': 'CHX',
	Chesham: 'CHE',
	Chesnut: 'CHT',
	Chigwell: 'CHG',
	Chingford: 'CFD',
	'Chiswick Park': 'CHP',
	Chorleywood: 'CWD',
	'Church Stret': 'CCS',
	'Clapham Common': 'CPC',
	'Clapham High Steet': 'CHS',
	'Clapham Junction': 'CLJ',
	'Clapham North': 'CPN',
	'Clapham South': 'CPS',
	Clapton: 'CPT',
	Cockfosters: 'CFS',
	Colindale: 'COL',
	'Colliers Wood': 'CLW',
	'Coombe Lane': 'CLN',
	'Covent Garden': 'COV',
	Crossharbour: 'CRO',
	'Crouch Hill': 'CRH',
	Croxley: 'CRX',
	'Crystal Palace': 'CRP',
	'Custom House for ExCeL': 'CUH',
	'Cutty Sark for Maritime Greenwich': 'CUS',
	Cyprus: 'CYP',
	'Dagenham East': 'DGE',
	'Dagenham Heathway': 'DGH',
	'Dalston Junction': 'DLJ',
	'Dalston Kingsland': 'DLK',
	Debden: 'DEB',
	'Denmark Hill': 'DMH',
	'Deptford Bridge': 'DEB',
	'Devons Road': 'DER',
	'Dollis Hill': 'DHL',
	'Dundonald Road': 'DDR',
	'Ealing Broadway': 'EBY',
	'Ealing Common': 'ECM',
	"Earl's Court": 'ECT',
	'East Acton': 'EAC',
	'East Croydon': 'ECR',
	'East Finchley': 'EFY',
	'East Ham': 'EHM',
	'East India': 'EAI',
	'East Putney': 'EPY',
	Eastcote: 'ETE',
	Edgware: 'EDG',
	'Edgware Road (Bakerloo line)': 'ERB',
	'Edgware Road (District, Circle, H&C lines)': 'ERD',
	'Edmonton Green': 'EMG',
	'Elephant & Castle': 'ELE',
	'Elmers End': 'ELM',
	'Elm Park': 'EPK',
	'Elverson Road': 'ELR',
	Embankment: 'EMB',
	'Emerson Park': 'EMP',
	'Emirates Greenwich Peninsula': 'EGP',
	'Emirates Royal Docks': 'EMD',
	'Enfield Town': 'EFT',
	Epping: 'EPP',
	Euston: 'EUS',
	'Euston Square': 'ESQ',
	Fairlop: 'FLP',
	Farringdon: 'FAR',
	Fieldway: 'FLW',
	'Finchley Central': 'FYC',
	'Finchley Road': 'FRD',
	'Finchley Road & Frognal': 'FNY',
	'Finsbury Park': 'FPK',
	'Forest Gate': 'FGT',
	'Forest Hill': 'FOH',
	'Fulham Broadway': 'FBY',
	'Gallions Reach': 'GAR',
	'Gants Hill': 'GHL',
	'George Street': 'GGS',
	'Gidea Park': 'GDP',
	'Gloucester Road': 'GRD',
	'Goldhawk Road': 'GOR',
	'Golders Green': 'GGR',
	'Goodge Street': 'GST',
	Goodmayes: 'GDM',
	'Gospel Oak': 'GPO',
	'Grange Hill': 'GRH',
	'Gravel Hill': 'GVH',
	'Great Portland Street': 'GPS',
	'Green Park': 'GPK',
	Greenford: 'GFD',
	Greenwich: 'GRE',
	Gunnersbury: 'GUN',
	'Hackney Central': 'HKC',
	'Hackney Downs': 'HKD',
	'Hackney Wick': 'HKW',
	Haggerston: 'HGG',
	Hainault: 'HAI',
	'Hammersmith (Circle, H&C lines)': 'HMS',
	'Hammersmith (District, Piccadilly lines)': 'HMD',
	Hampstead: 'HMP',
	'Hampstead Heath': 'HDH',
	'Hanger Lane': 'HLN',
	Hanwell: 'HWL',
	Harlesden: 'HSD',
	'Harringay Green Lanes': 'HRY',
	'Harrington Road': 'HRD',
	'Harold Wood': 'HWD',
	'Harrow & Wealdstone': 'HAW',
	'Harrow on the Hill': 'HOH',
	'Hatch End': 'HTE',
	'Hatton Cross': 'HTX',
	'Hayes & Harrlington': 'HAH',
	'Headstone Lane': 'HDL',
	'Heathrow Terminal 4': 'HTF',
	'Heathrow Terminal 5': 'HRV',
	'Heathrow Terminals 123': 'HRC',
	'Hendon Central': 'HND',
	'Heron Quays': 'HEQ',
	'Highams Park': 'HGP',
	'High Barnet': 'HBT',
	'High Street Kensington': 'HST',
	'Highbury & Islington': 'HBY',
	Highgate: 'HIG',
	Hillingdon: 'HDN',
	Holborn: 'HOL',
	'Holland Park': 'HPK',
	'Holloway Road': 'HRD',
	Homerton: 'HMN',
	'Honor Oak Park': 'HPA',
	Hornchurch: 'HCH',
	'Hounslow Central': 'HNC',
	'Hounslow East': 'HNE',
	'Hounslow West': 'HNW',
	Hoxton: 'HOX',
	'Hyde Park Corner': 'HPC',
	Ickenham: 'ICK',
	Ilford: 'IFD',
	'Imperial Wharf': 'IMW',
	'Island Gardens': 'ISG',
	Iver: 'IVR',
	Kennington: 'KEN',
	'Kensal Green': 'KGN',
	'Kensal Rise': 'KNR',
	'Kensington (Olympia)': 'OLY',
	'Kentish Town': 'KTN',
	'Kentish Town West': 'KTW',
	Kenton: 'KNT',
	'Kew Gardens': 'KEW',
	Kilburn: 'KIL',
	'Kilburn Park': 'KPK',
	'Kilburn High Road': 'KBN',
	'King George V': 'KGV',
	'King Henrys Drive': 'KHD',
	'Kings Cross St Pancras': 'KXX',
	'Kings Cross (Met, Circle, H&C lines)': 'KXX',
	'Kings Cross (Piccadilly, Victoria lines)': 'KXX',
	Kingsbury: 'KBY',
	Knightsbridge: 'KNB',
	'Ladbroke Grove': 'LAD',
	'Lambeth North': 'LAM',
	'Lancaster Gate': 'LAN',
	Langley: 'LGY',
	'Langdon Park': 'LAP',
	'Latimer Road': 'LAT',
	'Lebanon Road': 'LEB',
	'Leicester Square': 'LSQ',
	Lewisham: 'LEW',
	Leyton: 'LEY',
	'Leyton Midland Road': 'LEM',
	Leytonstone: 'LYS',
	'Leytonstone High Road': 'LER',
	Limehouse: 'LIM',
	'Liverpool Street': 'LST',
	'Lloyd Park': 'LPK',
	'London Bridge': 'LON',
	'London City Airport': 'LCA',
	'London Fields': 'LFD',
	Loughton: 'LTN',
	'Maida Vale': 'MDV',
	Maidenhead: 'MDH',
	'Manor House': 'MNR',
	'Manor Park': 'MNP',
	'Mansion House': 'MAN',
	'Marble Arch': 'MAR',
	Maryland: 'MLD',
	Marylebone: 'MYB',
	'Merton Park': 'MRP',
	'Mile End': 'MLE',
	'Mill Hill East': 'MHE',
	Mitcham: 'MTM',
	'Mitcham Junction': 'MTJ',
	Monument: 'MON',
	'Moor Park': 'MPK',
	Moorgate: 'MGT',
	Morden: 'MOR',
	'Morden Road': 'MRD',
	'Mornington Crescent': 'MCR',
	Mudchute: 'MUD',
	Neasden: 'NEA',
	'Newbury Park': 'NEP',
	'New Addington': 'NAD',
	'New Cross': 'NWX',
	'New Cross Gate': 'NXG',
	'Nine Elms': 'NIE',
	'North Acton': 'NAC',
	'North Ealing': 'NEL',
	'North Greenwich': 'NGW',
	'North Harrow': 'NHR',
	'North Wembley': 'NWM',
	Northfields: 'NFD',
	Northolt: 'NHT',
	'Northwick Park': 'NWP',
	Northwood: 'NWD',
	'Northwood Hills': 'NWH',
	'Norwood Junction': 'NJN',
	'Notting Hill Gate': 'NHG',
	Oakwood: 'OAK',
	'Old Street': 'OLD',
	Osterley: 'OST',
	Oval: 'OVL',
	'Oxford Circus': 'OXC',
	Paddington: 'PAD',
	'Paddington (Bakerloo, Circle/District and H&C)': 'PAD',
	'Park Royal': 'PRY',
	'Parsons Green': 'PGR',
	'Peckham Rye': 'PMR',
	'Penge West': 'PNW',
	Perivale: 'PER',
	'Phipps Bridge': 'PBR',
	'Piccadilly Circus': 'PIC',
	Pimlico: 'PIM',
	Pinner: 'PIN',
	Plaistow: 'PLW',
	'Pontoon Dock': 'PDK',
	Poplar: 'POP',
	'Preston Road': 'PRD',
	'Prince Regent': 'PRR',
	'Pudding Mill Lane': 'PML',
	'Putney Bridge': 'PUT',
	"Queen's Park": 'QPK',
	"Queen's Road Peckham": 'QRP',
	Queensbury: 'QBY',
	Queensway: 'QWY',
	'Ravenscourt Park': 'RCP',
	'Rayners Lane': 'RLN',
	Reading: 'RDG',
	'Rectory Road': 'RRD',
	Redbridge: 'RED',
	'Reeves Corner': 'RVC',
	"Regent's Park": 'RPK',
	Richmond: 'RMD',
	Rickmansworth: 'RKY',
	'Roding Valley': 'ROD',
	Rotherhithe: 'ROE',
	Romford: 'RFD',
	'Royal Albert': 'ROA',
	'Royal Oak': 'ROO',
	'Royal Victoria': 'ROV',
	Ruislip: 'RUI',
	'Ruislip Gardens': 'RUG',
	'Ruislip Manor': 'RUM',
	'Russell Square': 'RSQ',
	Sandilands: 'SAN',
	'Seven Kings': 'SVK',
	'Seven Sisters': 'SVS',
	Shadwell: 'SHA',
	Shenfield: 'SND',
	"Shepherd's Bush": 'SHB',
	"Shepherd's Bush (Central line)": 'SHB',
	"Shepherd's Bush Market": 'SBM',
	'Shoreditch High Street': 'SDC',
	'Silver Street': 'SST',
	'Sloane Square': 'SSQ',
	Slough: 'SGH',
	Snaresbrook: 'SNB',
	'South Acton': 'SAT',
	'South Ealing': 'SEL',
	'South Harrow': 'SHR',
	'South Hampstead': 'SOH',
	'South Kensington': 'SKN',
	'South Kenton': 'SKT',
	'South Tottenham': 'STO',
	'South Quay': 'SOQ',
	'South Ruislip': 'SRP',
	'South Wimbledon': 'SWM',
	'South Woodford': 'SWF',
	Southall: 'SAL',
	Southbury: 'SBY',
	Southfields: 'SFS',
	Southgate: 'SGT',
	Southwark: 'SWK',
	"St John's Wood": 'SJW',
	"St Paul's": 'STP',
	"St James' Park": 'SJP',
	"St James' Street": 'SJS',
	'Stamford Brook': 'STB',
	'Stamford Hill': 'SFH',
	Stanmore: 'STA',
	'Star Lane': 'STL',
	'Stepney Green': 'STG',
	Stockwell: 'STK',
	'Stoke Newington': 'SNT',
	'Stonebridge Park': 'SPK',
	Stratford: 'SFD',
	'Stratford High Street': 'SHS',
	'Stratford International': 'STI',
	'Sudbury Hill': 'SHL',
	'Sudbury Town': 'STN',
	'Surrey Quays': 'SUQ',
	'Swiss Cottage': 'SWC',
	Sydenham: 'SYD',
	Taplow: 'TLW',
	Temple: 'TEM',
	'Theobalds Grove': 'TBG',
	'Therapia Lane': 'TRL',
	'Theydon Bois': 'THB',
	'Tooting Bec': 'TBE',
	'Tooting Broadway': 'TBY',
	'Tottenham Court Road': 'TCR',
	'Tottenham Hale': 'TTH',
	'Totteridge & Whetstone': 'TOT',
	'Tower Gateway': 'TOG',
	'Tower Hill': 'THL',
	'Tufnell Park': 'TPK',
	'Turkey Street': 'TST',
	'Turnham Green': 'TGR',
	'Turnpike Lane': 'TPL',
	Twyford: 'TFD',
	Upminster: 'UPM',
	'Upminster Bridge': 'UPB',
	Upney: 'UPY',
	'Upper Holloway': 'UHL',
	'Upton Park': 'UPK',
	Uxbridge: 'UXB',
	Vauxhall: 'VUX',
	Victoria: 'VIC',
	'Waddon Marsh': 'WDM',
	'Walthamstow Central': 'WAL',
	"Walthamstow Queen's Road": 'WMW',
	'Wandle Park': 'WLP',
	'Wandsworth Road': 'WWR',
	Wanstead: 'WAN',
	'Wantead Park': 'WNP',
	Wapping: 'WPE',
	'Warren Street': 'WST',
	'Warwick Avenue': 'WAR',
	Waterloo: 'WLO',
	Watford: 'WAT',
	'Watford High Street': 'WFH',
	'Watford Junction': 'WTJ',
	'Wellesley Road': 'WLR',
	'Wembley Central': 'WEM',
	'Wembley Park': 'WPK',
	'Westbourne Park': 'WBP',
	'West Acton': 'WAC',
	'West Brompton': 'WBT',
	'West Croydon': 'WCY',
	'West Drayton': 'WDT',
	'West Ealing': 'WEL',
	'West Finchley': 'WFY',
	'West Ham': 'WEH',
	'West Hampstead': 'WHD',
	'West Harrow': 'WHR',
	'West India Quay': 'WIQ',
	'West Kensington': 'WKN',
	'West Ruislip': 'WRP',
	'West Silvertown': 'WSN',
	Westferry: 'WES',
	Westminster: 'WMS',
	'White City': 'WCT',
	Whitechapel: 'WCL',
	'White Heart Lane': 'WHL',
	'Willesden Green': 'WLG',
	'Willesden Junction': 'WJN',
	Wimbledon: 'WDN',
	'Wimbledon Park': 'WMP',
	'Wood Green': 'WGN',
	Woodford: 'WFD',
	'Woodgrange Park': 'WGR',
	'Wood Lane': 'WOL',
	Woodside: 'WDS',
	'Woodside Park': 'WSP',
	'Wood Street': 'WOS',
	'Woolwich Arsenal': 'WOA',
	Woolwich: 'WOO'
};
